import type { Metadata } from "next";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const OauthClientId = process.env.GOOGLE_AUTH_CLIENT_ID as string

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body style={{backgroundColor : "black"}}>
        <GoogleOAuthProvider clientId={OauthClientId}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
